// Patch payloads the nine patch pages are tested against. Every page is its
// own view over the same `GET /api/patches/:id` answer, so the fixtures are
// shared rather than written out once per page.

export const krellPatch = {
  id: 7,
  name: 'Krell',
  description: null,
  rack_id: 1,
  rack_name: 'main rack',
  created_at: '2026-08-12T10:00:00Z',
  modules: [
    {
      id: 11,
      module_id: 1,
      manufacturer: 'Make Noise',
      module_name: 'Maths',
      instance: 1,
      live: true,
      components: [
        { id: 1, type: 'input_jack', name: 'Signal In', values: [] },
        { id: 2, type: 'output_jack', name: 'EOR', values: [] },
        {
          id: 3,
          type: 'knob',
          name: 'Rise',
          values: [
            { id: 1, type: 'min', value: '0' },
            { id: 2, type: 'max', value: '10' },
          ],
        },
        {
          id: 4,
          type: 'switch',
          name: 'Mode',
          values: [
            { id: 3, type: 'enum', value: 'Cycle' },
            { id: 4, type: 'enum', value: 'Sustain' },
          ],
        },
      ],
    },
    {
      id: 12,
      module_id: 2,
      manufacturer: 'ALM',
      module_name: 'Pam',
      instance: 1,
      live: false,
      components: [],
    },
    {
      id: 13,
      module_id: 3,
      manufacturer: 'Doepfer',
      module_name: 'A-180-2',
      instance: 1,
      live: true,
      components: [
        { id: 5, type: 'bidirectional_jack', name: 'M1', group_label: '1', values: [] },
        { id: 6, type: 'bidirectional_jack', name: 'M2', group_label: '1', values: [] },
      ],
    },
  ],
  cables: [
    {
      id: 21,
      from_patch_module_id: 11,
      from_component_id: 2,
      from_component_name: 'EOR',
      to_patch_module_id: 11,
      to_component_id: 1,
      to_component_name: 'Signal In',
    },
  ],
  settings: [
    { id: 31, patch_module_id: 11, component_id: 3, component_name: 'Rise', value: '7' },
  ],
  normalizations: [
    {
      patch_module_id: 11,
      normalization_id: 41,
      target_component_id: 1,
      target_component_name: 'Signal In',
      source_component_id: null,
      source_component_name: null,
      source_label: 'internal oscillator',
      kind: 'internal',
      description: null,
      active: false,
      overriding_cable_id: 21,
      signals: [],
    },
    {
      patch_module_id: 13,
      normalization_id: 42,
      target_component_id: 6,
      target_component_name: 'M2',
      source_component_id: 5,
      source_component_name: 'M1',
      source_label: null,
      kind: 'input',
      description: null,
      active: true,
      overriding_cable_id: null,
      signals: [
        {
          kind: 'cable',
          cable_id: 21,
          from_patch_module_id: 11,
          from_component_id: 2,
          from_component_name: 'EOR',
          via: ['M1'],
        },
      ],
    },
  ],
  flow: [
    {
      key: 'pm11:c2',
      kind: 'jack',
      patch_module_id: 11,
      component_id: 2,
      name: 'EOR',
      jack_type: 'output_jack',
      via: null,
      merge: false,
      cycle: false,
      children: [
        {
          key: 'pm13:c5',
          kind: 'jack',
          patch_module_id: 13,
          component_id: 5,
          name: 'M1',
          jack_type: 'bidirectional_jack',
          via: 'cable',
          merge: false,
          cycle: false,
          children: [
            {
              key: 'pm13:c6',
              kind: 'jack',
              patch_module_id: 13,
              component_id: 6,
              name: 'M2',
              jack_type: 'bidirectional_jack',
              via: 'mult',
              merge: true,
              cycle: false,
              children: [
                {
                  key: 'pm13:c5',
                  kind: 'jack',
                  patch_module_id: 13,
                  component_id: 5,
                  name: 'M1',
                  jack_type: 'bidirectional_jack',
                  via: 'route',
                  merge: false,
                  cycle: true,
                  children: [],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};

// Everything a patch records beyond its cables: buses, labels, off-rack gear,
// a bridged pair, a conditional default and a traced flow.
export const richPatch = {
  id: 7,
  name: 'Full system',
  description: null,
  rack_id: 1,
  rack_name: 'main rack',
  created_at: '2026-08-12T10:00:00Z',
  modules: [
    {
      id: 11,
      module_id: 1,
      manufacturer: 'Erica Synths',
      module_name: 'LXR',
      instance: 1,
      label: 'snare voice',
      group_id: 5,
      external: false,
      live: true,
      components: [{ id: 1, type: 'output_jack', name: 'OUT', values: [] }],
    },
    {
      id: 12,
      module_id: null,
      manufacturer: 'external',
      module_name: 'UMC404HD',
      instance: 1,
      label: 'the computer',
      group_id: null,
      external: true,
      live: false,
      components: [
        { id: 90, type: 'output_jack', name: 'MIDI OUT', port_kind: 'midi_din', declared: true, values: [] },
      ],
    },
    {
      id: 13,
      module_id: 4,
      manufacturer: 'Omnitone',
      module_name: '7Path',
      instance: 1,
      label: null,
      group_id: null,
      external: false,
      live: true,
      components: [{ id: 7, type: 'bidirectional_jack', name: '1', values: [] }],
    },
  ],
  groups: [{ id: 5, name: 'Rhythm', description: null, position: 1 }],
  links: [
    {
      id: 81,
      kind: 'bridge',
      a_patch_module_id: 13,
      b_patch_module_id: 11,
      description: null,
      jacks: [{ id: 1, a_component_id: 7, a_component_name: '1', b_component_id: 1, b_component_name: '1' }],
    },
  ],
  cables: [
    {
      id: 21,
      from_patch_module_id: 12,
      from_component_id: 90,
      from_component_name: 'MIDI OUT',
      to_patch_module_id: 11,
      to_component_id: 1,
      to_component_name: 'OUT',
      note: 'adds the distortion layer',
      optional: true,
      stacked: true,
      alt_group: 'drive choice',
    },
  ],
  settings: [],
  pairs: [],
  normalizations: [
    {
      patch_module_id: 11,
      normalization_id: 41,
      target_component_id: 1,
      target_component_name: 'R',
      source_component_id: 2,
      source_component_name: 'L',
      source_label: null,
      kind: 'output',
      break_component_name: 'L',
      break_on: 'cable_out',
      condition: { component_name: 'MIX 4', value: 'up', state: 'unset' },
      alt_group: 'mix',
      exclusive: true,
      description: null,
      active: false,
      overriding_cable_id: 21,
      signals: [],
    },
  ],
  flow: [
    {
      key: 'pm12:c90',
      kind: 'jack',
      patch_module_id: 12,
      component_id: 90,
      name: 'MIDI OUT',
      jack_type: 'output_jack',
      port_kind: 'midi_din',
      via: null,
      switched: false,
      conditional: false,
      condition: null,
      merge: false,
      switched_merge: false,
      cycle: false,
      truncated: false,
      truncated_tree: true,
      children: [
        {
          key: 'pm13:c7',
          kind: 'jack',
          patch_module_id: 13,
          component_id: 7,
          name: '1',
          jack_type: 'bidirectional_jack',
          port_kind: null,
          via: 'bridge',
          switched: false,
          conditional: true,
          condition: { component_name: 'MIX 4', value: 'up', state: 'unset' },
          optional: true,
          merge: false,
          switched_merge: false,
          cycle: false,
          truncated: true,
          children: [],
        },
      ],
    },
  ],
};

// A patch built from a system spans several racks, and then which case a
// module stands in is part of knowing which module it is.
export const systemPatch = {
  id: 8,
  name: 'Whole studio',
  description: null,
  rack_id: null,
  rack_name: 'studio',
  system_id: 4,
  system_name: 'studio',
  created_at: '2026-08-12T10:00:00Z',
  modules: [
    {
      id: 11,
      module_id: 1,
      manufacturer: 'Make Noise',
      module_name: 'Maths',
      instance: 1,
      rack_id: 10,
      rack_name: 'left case',
      live: true,
      components: [{ id: 2, type: 'output_jack', name: 'Out', values: [] }],
    },
    {
      id: 12,
      module_id: 2,
      manufacturer: 'Mutable',
      module_name: 'Plaits',
      instance: 1,
      rack_id: 11,
      rack_name: 'right case',
      live: true,
      components: [{ id: 3, type: 'input_jack', name: 'In', values: [] }],
    },
  ],
  cables: [],
  settings: [],
  normalizations: [],
  groups: [],
  links: [],
  pairs: [],
  flow: { sources: [] },
  rack_layout: [
    { id: 100, rack_id: 10, rack_name: 'left case', unit: 3, hp: 84, modules: [11] },
    { id: 101, rack_id: 11, rack_name: 'right case', unit: 3, hp: 84, modules: [12] },
  ],
};
