// What /api/performances answers, as the views are tested against it.

export const performancePage = {
  total: 2,
  limit: 50,
  has_more: false,
  next_before: null,
  performances: [
    {
      id: 7,
      user_id: 2,
      owner_username: 'bob',
      title: 'Kitchen table drone',
      description: null,
      url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      video_id: 'dQw4w9WgXcQ',
      public: true,
      patch: null,
      mine: false,
      can_delete: false,
      module_count: 0,
      comment_count: 2,
      created_at: '2026-10-01T10:00:00Z',
      updated_at: '2026-10-01T10:00:00Z',
    },
    {
      id: 3,
      user_id: 1,
      owner_username: 'alice',
      title: 'Evening set',
      description: 'Krell patch, slowed down',
      url: 'https://www.youtube.com/watch?v=abcdefghijk',
      video_id: 'abcdefghijk',
      public: false,
      patch: { id: 12, name: 'Krell', live: true },
      mine: true,
      can_delete: true,
      module_count: 2,
      comment_count: 0,
      created_at: '2026-09-30T10:00:00Z',
      updated_at: '2026-09-30T10:00:00Z',
    },
  ],
};

export const performance = {
  id: 3,
  user_id: 1,
  owner_username: 'alice',
  title: 'Evening set',
  description: 'Krell patch, slowed down.\nListen for the sub.',
  url: 'https://www.youtube.com/watch?v=abcdefghijk',
  video_id: 'abcdefghijk',
  public: false,
  patch: { id: 12, name: 'Krell', live: true },
  mine: false,
  can_delete: false,
  modules: [
    { id: 5, manufacturer: 'Make Noise', name: 'Maths', hp: 20, summary: null, yours: true },
    { id: 6, manufacturer: 'Mutable', name: 'Plaits', hp: 12, summary: null, yours: false },
  ],
  comments: [
    {
      id: 1,
      performance_id: 3,
      user_id: 2,
      username: 'bob',
      body: 'Lovely patch',
      mine: true,
      can_delete: true,
      created_at: '2026-10-01T10:00:00Z',
      updated_at: '2026-10-01T10:00:00Z',
    },
    {
      id: 2,
      performance_id: 3,
      user_id: 1,
      username: 'alice',
      body: 'Thanks!',
      mine: false,
      can_delete: false,
      created_at: '2026-10-01T11:00:00Z',
      updated_at: '2026-10-01T11:00:00Z',
    },
  ],
  module_count: 2,
  comment_count: 2,
  created_at: '2026-09-30T10:00:00Z',
  updated_at: '2026-09-30T10:00:00Z',
};

export const performancePatch = {
  id: 12,
  name: 'Krell',
  description: null,
  rack_name: 'main rack',
  shared: true,
  owner_username: 'alice',
  modules: [],
  cables: [
    { id: 1, from_component_name: 'Maths EOR', to_component_name: 'Plaits Trigger', note: 'the clock' },
  ],
  settings: [{ id: 1, component_name: 'Plaits Model', value: 'Chords' }],
  switches: [],
  mults: [],
};
